=== singhuist/cyberbullying-detection/data/chatcoder/GeneralData/GeneralData/chatlog.dtd
<?xml version="1.0"?>
<!ELEMENT CHATLOG (PREDATOR+, VICTIM+, CODINGVERSION*, POST+)>
<!ELEMENT PREDATOR (FIRSTNAME, LASTNAME, STATEDNAME, STATEDAGE, GENDER, RACE, CITY, STATE, REPEATOFFENDER, ADMITGUILT, TRUTHFULNAME, SCREENNAME+)>
<!ELEMENT VICTIM (FIRSTNAME, LASTNAME, STATEDNAME, STATEDAGE, GENDER, RACE, CITY, STATE, PREVIOUSVICTIMIZATION, ADMITGUILT, SCREENNAME+)>
<!ELEMENT FIRSTNAME (#PCDATA)>
<!ELEMENT LASTNAME (#PCDATA)>
<!ELEMENT STATEDNAME (#PCDATA)>
<!ELEMENT STATEDAGE (#PCDATA)>
<!ELEMENT GENDER (#PCDATA)>
<!ELEMENT RACE (#PCDATA)>
<!ELEMENT CITY (#PCDATA)>
<!ELEMENT STATE (#PCDATA)>
<!ELEMENT PREVIOUSVICTIMIZATION (#PCDATA)>
<!ELEMENT ADMITGUILT (#PCDATA)>
<!ELEMENT TRUTHFULNAME (#PCDATA)>

<!ELEMENT SCREENNAME (USERNAME, HOST)>
<!ELEMENT USERNAME (#PCDATA)>
<!ELEMENT HOST (#PCDATA)>

<!ELEMENT CODINGVERSION (NAME, CODER)>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT CODER (#PCDATA)>

<!ELEMENT POST (USERNAME, DATETIME, BODY, COMMENT, CODING)>
<!ELEMENT DATETIME (#PCDATA)>
<!ELEMENT BODY (#PCDATA)>
<!ELEMENT COMMENT (#PCDATA)>
<!ELEMENT CODING (VERSION, CATEGORY, TONE)>
<!ELEMENT VERSION (#PCDATA)>
<!ELEMENT CATEGORY (#PCDATA)>
<!ELEMENT TONE (#PCDATA)>

=== singhuist/cyberbullying-detection/data/chatcoder/GeneralData/GeneralData/m4pixeleen.xml
<!DOCTYPE CHATLOG SYSTEM 'chatlog.dtd'>
<CHATLOG>
<PREDATOR>
<FIRSTNAME>Stephen</FIRSTNAME>
<LASTNAME>Coates</LASTNAME>
<STATEDNAME>Stephen</STATEDNAME>
<STATEDAGE>42</STATEDAGE>
<AGE>60</AGE>
<GENDER>Male</GENDER>
<RACE>White</RACE>
<CITY>Los Angeles</CITY>
<STATE>CA</STATE>
<REPEATOFFENDER>false</REPEATOFFENDER>
<ADMITGUILT>false</ADMITGUILT>
<TRUTHFULNAME>true</TRUTHFULNAME>
<SCREENNAME>
<USERNAME>m4pixeleen</USERNAME>
<HOST></HOST>
</SCREENNAME>
</PREDATOR>
<VICTIM>
<FIRSTNAME>Almond</FIRSTNAME>
<LASTNAME>Joy</LASTNAME>
<STATEDNAME>Ame</STATEDNAME>
<STATEDAGE>13</STATEDAGE>
<GENDER>Female</GENDER>
<RACE></RACE>
<CITY>Riverside</CITY>
<STATE>CA</STATE>
<PREVIOUSVICTIMIZATION>false</PREVIOUSVICTIMIZATION>
<ADMITGUILT>false</ADMITGUILT>
<SCREENNAME>
<USERNAME>greendaychickk</USERNAME>
<HOST></HOST>
</SCREENNAME>
</VICTIM>
<CODINGVERSION>
<NAME>m4pixeleen.emjakubowski.coded.txt</NAME>
<CODER>emjakubowski</CODER>
</CODINGVERSION>
<POST>
<USERNAME>m4pixeleen</USERNAME>
<DATETIME>(7:54:52 pm)</DATETIME>
<BODY>hi...what city? i'm m/42/los angeles...for discreet lady</BODY>
<COMMENT></COMMENT>
<CODING>
<VERSION>m4pixeleen.emjakubowski.coded.txt</VERSION>
<CATEGORY>200</CATEGORY>
<TONE>21</TONE>
</CODING>
</POST>
<POST>
<USERNAME>greendaychickk</USERNAME>
<DATETIME>(7:55:29 pm)</DATETIME>
<BODY>13 f riverside</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>m4pixeleen</USERNAME>
<DATETIME>(7:55:41 pm)</DATETIME>
<BODY>nice pic</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>m4pixeleen</USERNAME>
<DATETIME>(7:55:48 pm)</DATETIME>
<BODY>lonely without your frieinds?</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>greendaychickk</USERNAME>
<DATETIME>(7:56:07 pm)</DATETIME>
<BODY>yea</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>m4pixeleen</USERNAME>
<DATETIME>(7:56:18 pm)</DATETIME>
<BODY>how is school there?</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>greendaychickk</USERNAME>
<DATETIME>(7:56:57 pm)</DATETIME>
<BODY>its ok</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>m4pixeleen</USERNAME>
<DATETIME>(7:58:01 pm)</DATETIME>
<BODY>any new friends?</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>greendaychickk</USERNAME>
<DATETIME>(7:58:13 pm)</DATETIME>
<BODY>a coupl</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>m4pixeleen</USERNAME>
<DATETIME>(7:58:25 pm)</DATETIME>
<BODY>that's good</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>m4pixeleen</USERNAME>
<DATETIME>(7:58:34 pm)</DATETIME>
<BODY>been on yahoo long? or just myspace?</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>greendaychickk</USERNAME>
<DATETIME>(7:59:16 pm)</DATETIME>
<BODY>i had a old pro but i cudnt chat ne more</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>m4pixeleen</USERNAME>
<DATETIME>(7:59:39 pm)</DATETIME>
<BODY>what is old pro?</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>greendaychickk</USERNAME>
<DATETIME>(7:59:48 pm)</DATETIME>
<BODY>old yahoo profile</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>m4pixeleen</USERNAME>
<DATETIME>(8:00:59 pm)</DATETIME>
<BODY>ok..what are you into?</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>greendaychickk</USERNAME>
<DATETIME>(8:01:30 pm)</DATETIME>
<BODY>hm i like 2 chat</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>greendaychickk</USERNAME>
<DATETIME>(8:01:44 pm)</DATETIME>
<BODY>with my freinds in nm</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>m4pixeleen</USERNAME>
<DATETIME>(8:01:48 pm)</DATETIME>
<BODY>ok</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>greendaychickk</USERNAME>
<DATETIME>(8:01:51 pm)</DATETIME>
<BODY>and listen to music</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>greendaychickk</USERNAME>
<DATETIME>(8:01:57 pm)</DATETIME>
<BODY>i luv greenday</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>m4pixeleen</USERNAME>
<DATETIME>(8:02:51 pm)</DATETIME>
<BODY>thy are cool</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>m4pixeleen</USERNAME>
<DATETIME>(8:03:19 pm)</DATETIME>
<BODY>i write songs myself</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>greendaychickk</USERNAME>
<DATETIME>(8:03:27 pm)</DATETIME>
<BODY>realy??!!!1</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>m4pixeleen</USERNAME>
<DATETIME>(8:03:37 pm)</DATETIME>
<BODY>yes</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>greendaychickk</USERNAME>
<DATETIME>(8:03:41 pm)</DATETIME>
<BODY>kewl</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>m4pixeleen</USERNAME>
<DATETIME>(8:03:47 pm)</DATETIME>
<BODY>i'm trying to sell them</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>m4pixeleen</USERNAME>
<DATETIME>(8:07:46 pm)</DATETIME>
<BODY>do you talk to a lot of people on line?</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>m4pixeleen</USERNAME>
<DATETIME>(8:08:10 pm)</DATETIME>
<BODY>my songs are pop rock, some adult contemporary and blues</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>greendaychickk</USERNAME>
<DATETIME>(8:08:14 pm)</DATETIME>
<BODY>no</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>m4pixeleen</USERNAME>
<DATETIME>(8:08:33 pm)</DATETIME>
<BODY>just your buddies i take it</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>greendaychickk</USERNAME>
<DATETIME>(8:08:49 pm)</DATETIME>
<BODY>yea</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>m4pixeleen</USERNAME>
<DATETIME>(8:09:05 pm)</DATETIME>
<BODY>ok...well be careful on yahoo</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>m4pixeleen</USERNAME>
<DATETIME>(8:09:19 pm)</DATETIME>
<BODY>some strange people</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>greendaychickk</USERNAME>
<DATETIME>(8:09:47 pm)</DATETIME>
<BODY>lol yea</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>m4pixeleen</USERNAME>
<DATETIME>(8:09:56 pm)</DATETIME>
<BODY>do you talk about sex and things like that?</BODY>
<COMMENT></COMMENT>
<CODING>
<VERSION>m4pixeleen.emjakubowski.coded.txt</VERSION>
<CATEGORY>600</CATEGORY>
<TONE>2</TONE>
</CODING>
</POST>
<POST>
<USERNAME>m4pixeleen</USERNAME>
<DATETIME>(8:10:09 pm)</DATETIME>
<BODY>you can tell me anything, it's ok</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>greendaychickk</USERNAME>
<DATETIME>(8:10:44 pm)</DATETIME>
<BODY>i have</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>m4pixeleen</USERNAME>
<DATETIME>(8:11:00 pm)</DATETIME>
<BODY>it is fun ;)</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>m4pixeleen</USERNAME>
<DATETIME>(8:11:11 pm)</DATETIME>
<BODY>been with any boys or men?</BODY>
<COMMENT></COMMENT>
<CODING>
<VERSION>m4pixeleen.emjakubowski.coded.txt</VERSION>
<CATEGORY>600</CATEGORY>
<TONE>2</TONE>
</CODING>
</POST>
<POST>
<USERNAME>greendaychickk</USERNAME>
<DATETIME>(8:11:41 pm)</DATETIME>
<BODY>been??</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>m4pixeleen</USERNAME>
<DATETIME>(8:11:53 pm)</DATETIME>
<BODY>in a sexy way</BODY>
<COMMENT></COMMENT>
<CODING>
<VERSION>m4pixeleen.emjakubowski.coded.txt</VERSION>
<CATEGORY>600</CATEGORY>
<TONE>3</TONE>
</CODING>
</POST>
<POST>
<USERNAME>greendaychickk</USERNAME>
<DATETIME>(8:12:00 pm)</DATETIME>
<BODY>oh</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>greendaychickk</USERNAME>
<DATETIME>(8:12:01 pm)</DATETIME>
<BODY>lol</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>greendaychickk</USERNAME>
<DATETIME>(8:12:03 pm)</DATETIME>
<BODY>soreta</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>m4pixeleen</USERNAME>
<DATETIME>(8:14:02 pm)</DATETIME>
<BODY>lol...kisses, touching?</BODY>
<COMMENT></COMMENT>
<CODING>
<VERSION>m4pixeleen.emjakubowski.coded.txt</VERSION>
<CATEGORY>600</CATEGORY>
<TONE>2</TONE>
</CODING>
</POST>
<POST>
<USERNAME>greendaychickk</USERNAME>
<DATETIME>(8:14:55 pm)</DATETIME>
<BODY>yea</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>m4pixeleen</USERNAME>
<DATETIME>(8:15:06 pm)</DATETIME>
<BODY>sucking?</BODY>
<COMMENT></COMMENT>
<CODING>
<VERSION>m4pixeleen.emjakubowski.coded.txt</VERSION>
<CATEGORY>600</CATEGORY>
<TONE>2</TONE>
</CODING>
</POST>
<POST>
<USERNAME>greendaychickk</USERNAME>
<DATETIME>(8:15:49 pm)</DATETIME>
<BODY>no</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>m4pixeleen</USERNAME>
<DATETIME>(8:16:29 pm)</DATETIME>
<BODY>ok....</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>m4pixeleen</USERNAME>
<DATETIME>(8:18:44 pm)</DATETIME>
<BODY>what greenday songs do you like best?</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>greendaychickk</USERNAME>
<DATETIME>(8:19:12 pm)</DATETIME>
<BODY>american idiot</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>m4pixeleen</USERNAME>
<DATETIME>(8:19:33 pm)</DATETIME>
<BODY>ok..how tall are you?</BODY>
<COMMENT></COMMENT>
<CODING>
<VERSION>m4pixeleen.emjakubowski.coded.txt</VERSION>
<CATEGORY>200</CATEGORY>
<TONE>2</TONE>
</CODING>
</POST>
<POST>
<USERNAME>greendaychickk</USERNAME>
<DATETIME>(8:19:42 pm)</DATETIME>
<BODY>5'1</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>m4pixeleen</USERNAME>
<DATETIME>(8:19:47 pm)</DATETIME>
<BODY>nice</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>m4pixeleen</USERNAME>
<DATETIME>(8:20:01 pm)</DATETIME>
<BODY>you seem like a very sweet girl</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>m4pixeleen</USERNAME>
<DATETIME>(8:20:14 pm)</DATETIME>
<BODY>i'm more your parent's age...is that ok with you?</BODY>
<COMMENT></COMMENT>
<CODING>
<VERSION>m4pixeleen.emjakubowski.coded.txt</VERSION>
<CATEGORY>600</CATEGORY>
<TONE>12</TONE>
</CODING>
</POST>
<POST>
<USERNAME>greendaychickk</USERNAME>
<DATETIME>(8:20:23 pm)</DATETIME>
<BODY>sure</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>m4pixeleen</USERNAME>
<DATETIME>(8:20:31 pm)</DATETIME>
<BODY>ok...are they cool people?</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>m4pixeleen</USERNAME>
<DATETIME>(8:20:50 pm)</DATETIME>
<BODY>i'm very open...so you can ask or talk to me about anything, ok?</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>greendaychickk</USERNAME>
<DATETIME>(8:20:59 pm)</DATETIME>
<BODY>ok</BODY>
<COMMENT></COMMENT>
</POST>
<POST>
<USERNAME>m4pixeleen</USERNAME>
<DATETIME>(8:21:10 pm)</DATETIME>
